### ISSUE TITLE
Incorrect frequency value. RaspberryPi 3 port.

### ISSUE THREAD

**Issue by tymion** [linaro-swg/arm-trusted-firmware#7]
Branch rpi3_initial_drop.
In file plat/rpi3/aarch64/rpi3_common.c there is function plat_get_syscnt_freq.
`
uint64_t plat_get_syscnt_freq(void)
{
    return 1200000;
}
`
Shouldn't this function return 12 MHz value? I think that there is one 0 missing.

**Comment by jforissier** [comment]
Hi @tymion ,

I don't know what the correct value should be. Where did you get 12 MHz from? I can see 19.2 MHz in a couple of places ([here](https://github.com/OP-TEE/build/blob/master/rpi3/firmware/head.S#L38-L39) and [here](https://github.com/gonzoua/rpi3-psci-monitor/blob/master/pscimon.S#L36) for instance). I don't know if this is documented somewhere -- doing some measurement may help...

**Comment by tymion** [comment]
Hi @jforissier ,
I have finally used 19.2 Mhz value and it work fine. Thanks for suggestion.

**Comment by jforissier** [comment]
Glad you got everything working ;-)
And FYI I think it is fixed in latest ARM-TF: https://github.com/ARM-software/arm-trusted-firmware/blob/3923bdb019f3d441ad9785d28b0bbdfb70bb17d5/plat/rpi3/include/platform_def.h#L227.
